apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-message-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-message-app
  template:
    metadata:
      labels:
        app: reverse-message-app
    spec:
      containers:
      - name: reverse-message-app
        image: reverse-message-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 4
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 4
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-message-app
spec:
  selector:
    app: reverse-message-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
