apiVersion: apps/v1
kind: Deployment
metadata:
  name: sap-node-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sap-node-app-1
  template:
    metadata:
      labels:
        app: sap-node-app-1
    spec:
      containers:
      - name: sap-node-app-1
        image: sap-node-app-1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 4
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 4
---
apiVersion: v1
kind: Service
metadata:
  name: sap-node-app-1
spec:
  selector:
    app: sap-node-app-1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
